// generated by compile -asmhdr from package aes

#define const_gcmBlockSize 16
#define const_gcmTagSize 16
#define const_gcmMinimumTagSize 12
#define const_gcmStandardNonceSize 12
#define gcmAsm__size 296
#define gcmAsm_ks 0
#define gcmAsm_productTable 24
#define gcmAsm_nonceSize 280
#define gcmAsm_tagSize 288
#define const_BlockSize 16
#define aesCipher__size 484
#define aesCipher_l 0
#define aesCipher_enc 4
#define aesCipher_dec 244
#define aesCipherAsm__size 484
#define aesCipherAsm_aesCipher 0
#define aesCipherGCM__size 484
#define aesCipherGCM_aesCipherAsm 0
#define const_poly 283
