
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/Leopere/ship-it/internal/gitx"


)

var tests = []testing.InternalTest{

	{"TestPullGetsLatestUpstreamCode", _test.TestPullGetsLatestUpstreamCode},

	{"TestShipStagesCommitsAndPushesEverything", _test.TestShipStagesCommitsAndPushesEverything},

	{"TestShipBypassesFailingHooksAndCommitSigning", _test.TestShipBypassesFailingHooksAndCommitSigning},

	{"TestCleanShipPushesAnExistingCommit", _test.TestCleanShipPushesAnExistingCommit},

	{"TestShipHandsOffOnlyAfterSuccessfulPush", _test.TestShipHandsOffOnlyAfterSuccessfulPush},

	{"TestPushDestinationMatchesBareGitPush", _test.TestPushDestinationMatchesBareGitPush},

	{"TestPushDestinationRejectsAmbiguousMappings", _test.TestPushDestinationRejectsAmbiguousMappings},

	{"TestDeployItPathPrefersSiblingThenPATH", _test.TestDeployItPathPrefersSiblingThenPATH},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/Leopere/ship-it/internal/gitx"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

