package main

import (
	"flag"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const marker = "SHIP_IT_SKILL"

const openAIYAML = `interface:
  display_name: "Ship It"
  short_description: "Ship changes and hand off explicit deployments"
  default_prompt: "Use $ship-it to sync this repository, make the requested changes, verify them once, ship everything, and hand the shipped revision to deploy-it."
`

func main() {
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	absRoot, err := filepath.Abs(*root)
	must(err)
	sourcePath := filepath.Join(absRoot, "internal", "skilldoc", "source.go")
	file, err := parser.ParseFile(token.NewFileSet(), sourcePath, nil, parser.ParseComments)
	must(err)

	var skill string
	for _, group := range file.Comments {
		for _, comment := range group.List {
			text := strings.TrimPrefix(strings.TrimSuffix(comment.Text, "*/"), "/*")
			text = strings.TrimPrefix(text, "\n")
			if strings.HasPrefix(text, marker+"\n") {
				skill = strings.TrimPrefix(text, marker+"\n")
			}
		}
	}
	if skill == "" {
		panic("SHIP_IT_SKILL comment not found")
	}
	if !strings.HasSuffix(skill, "\n") {
		skill += "\n"
	}

	generated := "// Code generated by cmd/genskill; DO NOT EDIT.\n\npackage skilldoc\n\n" +
		"const SkillMD = " + strconv.Quote(skill) + "\n\n" +
		"const OpenAIYAML = " + strconv.Quote(openAIYAML) + "\n"
	must(os.WriteFile(filepath.Join(absRoot, "internal", "skilldoc", "generated.go"), []byte(generated), 0o644))

	skillDir := filepath.Join(absRoot, "skill", "ship-it")
	must(os.MkdirAll(filepath.Join(skillDir, "agents"), 0o755))
	must(os.WriteFile(filepath.Join(skillDir, "SKILL.md"), []byte(skill), 0o644))
	must(os.WriteFile(filepath.Join(skillDir, "agents", "openai.yaml"), []byte(openAIYAML), 0o644))

	fmt.Println("generated skill/ship-it and internal/skilldoc/generated.go")
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
