
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/Leopere/ship-it/internal/app"


)

var tests = []testing.InternalTest{

	{"TestLifecycleMode", _test.TestLifecycleMode},

	{"TestHookTargetsPayloadRepositoriesAndSkipsBeforeGit", _test.TestHookTargetsPayloadRepositoriesAndSkipsBeforeGit},

	{"TestHookSkipsIrrelevantAndMalformedPayloadBeforeGit", _test.TestHookSkipsIrrelevantAndMalformedPayloadBeforeGit},

	{"TestHookWritesGitFailureToStderr", _test.TestHookWritesGitFailureToStderr},

	{"TestRepositoryDeliveryRejectsArguments", _test.TestRepositoryDeliveryRejectsArguments},

	{"TestBareLifecyclePullsThenShipsCompletedCycles", _test.TestBareLifecyclePullsThenShipsCompletedCycles},

	{"TestStopDeliversTouchedExternalRepositoryOnce", _test.TestStopDeliversTouchedExternalRepositoryOnce},

	{"TestTouchedDeliveryKeepsFailedAndNewerGenerations", _test.TestTouchedDeliveryKeepsFailedAndNewerGenerations},

	{"TestHookRootsRejectTrashComponentsBeforeRepositoryLookup", _test.TestHookRootsRejectTrashComponentsBeforeRepositoryLookup},

	{"TestTouchedRootRejectsForbiddenAliasAndMissingNestedRoot", _test.TestTouchedRootRejectsForbiddenAliasAndMissingNestedRoot},

	{"TestSessionStartDoesNotSelectTouchedRoots", _test.TestSessionStartDoesNotSelectTouchedRoots},

	{"TestTouchedFailureAllowsOnlyOneContinuationPerGeneration", _test.TestTouchedFailureAllowsOnlyOneContinuationPerGeneration},

	{"TestCleanFailedDeploymentRemainsPendingForNextTurn", _test.TestCleanFailedDeploymentRemainsPendingForNextTurn},

	{"TestTallyDelivery", _test.TestTallyDelivery},

	{"TestTallyDeliveryValidationAndScope", _test.TestTallyDeliveryValidationAndScope},

	{"TestTallyDeliveryTimeout", _test.TestTallyDeliveryTimeout},

	{"TestLegacyHookDetachedDelivery", _test.TestLegacyHookDetachedDelivery},

	{"TestLegacyHookContinuesAfterInvalidWorkspaceRoot", _test.TestLegacyHookContinuesAfterInvalidWorkspaceRoot},

	{"TestHasUnshippedWork", _test.TestHasUnshippedWork},

	{"TestFailedDeliveryAllowsOneCleanContinuation", _test.TestFailedDeliveryAllowsOneCleanContinuation},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ImportPath = "github.com/Leopere/ship-it/internal/app"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

